aweProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aweProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace aweProject.Controllers
{
    public class OrdersController : Controller
    {
        private readonly AppDbContext _context;

        public OrdersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        [Authorize(Roles = "Lagerist, Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(new SiteOrderRessources(await _context.Ressources.ToListAsync(), await _context.Order.ToListAsync(), await _context.SiteManagement.ToListAsync(), await _context.Retouren.ToListAsync()));
        }

        private bool OrderExists(Guid id)
        {
            return _context.Order.Any(e => e.OrderId == id);
        }

        public async Task<IActionResult> Checkout(Guid RessourceId, Guid SiteId, Guid OrderId) {
            Ressources ressource = await _context.Ressources.FindAsync(RessourceId);
            Order order = await _context.Order.FindAsync(OrderId);
            SiteManagement site = await _context.SiteManagement.FindAsync(SiteId);

            ressource.SiteId = SiteId;
            ressource.IsInStorage = false;
            ressource.OrderLog = ressource.OrderLog + DateTime.Now.ToString() + ", ";
            ressource.Standort = site.Name;
            order.IsActive = true;
            order.IsClosed = false;
            order.CheckOutTime = DateTime.Now;

            await _context.SaveChangesAsync();

            return PartialView("OrderPartial", new SiteOrderRessources(await _context.Ressources.ToListAsync(), await _context.Order.ToListAsync(), await _context.SiteManagement.ToListAsync(), await _context.Retouren.ToListAsync()));
        }
    }
}

aweProject/Controllers/RessourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aweProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace aweProject.Controllers
{
    public class RessourcesController : Controller
    {
        private readonly AppDbContext _context;

        public RessourcesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Ressources
        [Authorize(Roles = "Lagerist, Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ressources.ToListAsync());
        }

        // GET: Create Partial View
        public ActionResult GetCreate()
        {
            return PartialView("CreatePartial");
        }

        // POST: Insert Data from Create Partial View
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostInsert([Bind("Id,Name,Type,BuyDate,NextMaintenance,Standort, SiteId, OrderLog, IsInStorage")] Ressources ressources)
        {
            if (!ModelState.IsValid) return PartialView("CreatePartial", ressources);

            ressources.Id = Guid.NewGuid();
            ressources.SiteId = Guid.Empty;
            ressources.OrderLog = DateTime.Now.ToString() + ", ";
            ressources.Standort = "Lager";
            //ressources.OrderLog = "10/05/2021 14:11:31 ,14/05/2021 13:10:10, 29/06/2021 19:11:53, 30/06/2021 19:11:53, 07/07/2021 19:11:53";
            ressources.IsInStorage = true;
            _context.Add(ressources);
            await _context.SaveChangesAsync();
            return PartialView("IndexNewPartial", ressources);

        }

        // GET: Edit Partial View
        public async Task<IActionResult> GetEdit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var session = await _context.Ressources.FindAsync(id);
            if (session == null)
            {
                return NotFound();
            }

            return PartialView("EditPartial", session);
        }

        // POST: Update Data from Create Partial View
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PostUpdate([Bind("Id,Name,Type,BuyDate,NextMaintenance,Standort, SiteId, OrderLog, IsInStorage")] Ressources ressources)
        {
            if (ModelState.IsValid)
            {
                try
                {   
                    _context.Update(ressources);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RessourceExists(ressources.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return PartialView("IndexPartial", ressources);
            }
            return PartialView("EditPartial", ressources);
        }

        // GET: Get Index Partial (Edit Canceled)
        public async Task<IActionResult> GetCancelEdit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var session = await _context.Ressources.FirstOrDefaultAsync(m => m.Id == id);
            if (session == null)
            {
                return NotFound();
            }
            return PartialView("IndexPartial", session);
        }

        // GET: Get New Partial (Create Canceled)
        public ActionResult GetCancelCreate()
        {
            return PartialView("NewPartial");
        }

        // POST: Delete Data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PostDelete(Guid id)
        {
            var orderList = await _context.Order.ToListAsync();
            foreach (Order order in orderList)
            {
                if (order.RessourceId == id)
                {
                    _context.Order.Remove(order);
                    await _context.SaveChangesAsync();
                }
            }

            var retourenList = await _context.Retouren.ToListAsync();
            foreach (Retouren retoure in retourenList)
            {
                if (retoure.RessourceId == id)
                {
                    _context.Retouren.Remove(retoure);
                    await _context.SaveChangesAsync();
                }
            }

            var session = await _context.Ressources.FindAsync(id);
            _context.Ressources.Remove(session);
            await _context.SaveChangesAsync();
            return new EmptyResult();
        }

        private bool RessourceExists(Guid id)
        {
            return _context.Ressources.Any(e => e.Id == id);
        }

        // GET: GetDetailsPartial
        public async Task<IActionResult> GetDetails(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //string dates = "29/06/2021 19:11:53, 30/06/2021 19:11:53, 07/07/2021 19:11:53, 14/07/2021 16:52:13, 18/07/2021 14:01:33, ";
            var session = await _context.Ressources.FindAsync(id);
            //session.OrderLog = dates;
            if (session == null)
            {
                return NotFound();
            }

            ViewBag.Occupancy = CalculateTime(session.OrderLog);
            return PartialView("DetailsPartial", session);
        }

        public static double CalculateTime(String OrderLog)
        {
            string[] dateString = OrderLog.Split(',');          //split String into array
            List<DateTime> dates = new List<DateTime>();

            foreach (var date in dateString)
            {                   //convert String to DateTime List
                if (date.Equals(" ") | date.Equals(""))
                {
                    break;
                }
                else
                {
                    dates.Add(Convert.ToDateTime(date));
                }
            }

            double TotalTimeStorage = 0;
            double TotalTimeAway = 0;

            DateTime LastDate = DateTime.Now;
            int i = 0;
            TimeSpan ts = TimeSpan.Zero;

            foreach (var date in dates)
            {                        //count time between dates and calculate TotalTimeAway and TotalTimeStorage
                if (i == 0)
                {
                    LastDate = date;
                }
                else if (i % 2 == 0)
                {
                    ts = date - LastDate;
                    TotalTimeAway += ts.TotalSeconds;
                    LastDate = date;

                }
                else
                {
                    ts = date - LastDate;
                    TotalTimeStorage += ts.TotalSeconds;
                    LastDate = date;

                }
                i++;
            }
            return Math.Round(((Double)TotalTimeAway / (TotalTimeAway + TotalTimeStorage)) * 100, 2);  // Rückgabe Auslastung in % auf zwei Nachkommastellen gerundet
        }
    }
}

aweProject/Controllers/RetourensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aweProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace aweProject.Controllers
{
    public class RetourensController : Controller
    {
        private readonly AppDbContext _context;

        public RetourensController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Retourens
        [Authorize(Roles = "Lagerist, Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(new SiteOrderRessources(await _context.Ressources.ToListAsync(), await _context.Order.ToListAsync(), await _context.SiteManagement.ToListAsync(), await _context.Retouren.ToListAsync()));
        }

        private bool RetourenExists(Guid id)
        {
            return _context.Retouren.Any(e => e.RetourenId == id);
        }

        // TODO: Order löschen
        public async Task<IActionResult> CheckIn(Guid RessourceId, Guid SiteId, Guid RetourenId, Guid OrderId) {
            Ressources ressource = await _context.Ressources.FindAsync(RessourceId);
            Retouren retouren = await _context.Retouren.FindAsync(RetourenId);
            Order order = await _context.Order.FindAsync(OrderId);
            Console.WriteLine("übergebene id" + OrderId);
            Console.WriteLine(order.OrderId);
            order.IsClosed = true;
            order.IsActive = false;
            ressource.SiteId = SiteId;
            ressource.IsInStorage = true;
            ressource.OrderLog = ressource.OrderLog + DateTime.Now.ToString() + ", ";
            ressource.Standort = "Lager";
            retouren.IsActive = true;
            retouren.CheckInTime = DateTime.Now;
            
            await _context.SaveChangesAsync();

            return PartialView("RetourenPartial", new SiteOrderRessources(await _context.Ressources.ToListAsync(), await _context.Order.ToListAsync(), await _context.SiteManagement.ToListAsync(), await _context.Retouren.ToListAsync() ));
        }
    }
}

aweProject/Controllers/UserManagementController.cs
using aweProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace aweProject.Controllers
{
    public class UserManagementController : Microsoft.AspNetCore.Mvc.Controller
    {

        private  AppDbContext _context;


        public UserManagementController(AppDbContext context)
        {
            _context = context;
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Roles ="Administrator")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Roles = await _context.Roles.ToListAsync();
            return View(_context.Users.ToList());
        }

        [Microsoft.AspNetCore.Mvc.HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
           
  
            UserRole userRole = new UserRole();
            var users = _context.Users.Where(x => x.Id == Id).SingleOrDefault();
            var userInRole = _context.UserRoles.Where(x => x.UserId == Id).Select(x => x.RoleId).ToList();
            userRole.applicationUser = users;

            userRole.ApplicationRoles = await _context.Roles.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id,
                Selected = userInRole.Contains(x.Id)
            }).ToListAsync();
            
            return View(userRole);
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public async Task<IActionResult> Edit (UserRole model)
        {
            var applicationUser = await _context.Users.FindAsync(model.applicationUser.Id);
            var selectedRoleId = model.ApplicationRoles.Where(x => x.Selected).Select(x => x.Value);
            var AlreadyExists = _context.UserRoles.Where(x => x.UserId == model.applicationUser.Id).Select(x => x.RoleId).ToList();
            var toAdd = selectedRoleId.Except(AlreadyExists);
            var toRemove = AlreadyExists.Except(selectedRoleId);
            foreach (var item in toRemove)
            {
                _context.UserRoles.Remove(new Microsoft.AspNetCore.Identity.IdentityUserRole<string>
                {
                    RoleId = item,
                    UserId = model.applicationUser.Id
                });
            }
            foreach (var item in toAdd)
            {
                _context.UserRoles.Add(new Microsoft.AspNetCore.Identity.IdentityUserRole<string>
                {
                    RoleId = item,
                    UserId = model.applicationUser.Id
                });
            }
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

aweProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - aweProject</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <environment include="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link rel="stylesheet" href="~/css/site.css"/>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </environment>
    <environment exclude="Development">
        @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
               asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
               asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>

    <partial name="_ValidationScriptsPartial"/>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet">
    <link href="https://unpkg.com/gijgo@1.9.11/css/gijgo.min.css" rel="stylesheet"/>

    <script src="https://unpkg.com/gijgo@1.9.11/js/gijgo.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/navbar.css"/>
    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>

<div class="sidebar" id="sidebar">
    <div class="logo-details">
        <i class="bx bx-menu" id="closeBtn"></i>
        <div class="logo_name">WueDispatch</div>
    </div>
    <ul class="nav-list">

        <li>
            <a id="home" asp-controller="Home" asp-action="Index">
                <i class="fas fa-columns"></i>
                <span class="links_name">Dashboard</span>
            </a>
            <span class="tooltip">Dashboard</span>
        </li>

        <li>
            <a asp-controller="Orders" asp-action="Index">
                <i class="fas fa-sitemap"></i>
                <span class="links_name">Auftragsverwaltung</span>
            </a>
            <span class="tooltip">Auftragsverwaltung</span>
        </li>

        <li>
            <a asp-controller="SiteManagements" asp-action="Index">
                <i class="fas fa-drafting-compass"></i>
                <span class="links_name">Baustellenverwaltung</span>
            </a>
            <span class="tooltip">Baustellenverwaltung</span>
        </li>

        <li>
            <a asp-controller="Ressources" asp-action="Index">
                <i class="fas fa-tools"></i>
                <span class="links_name">Bestandsverwaltung</span>
            </a>
            <span class="tooltip">Bestandsverwaltung</span>
        </li>

        <li>
            <a asp-controller="Retourens" asp-action="Index">
                <i class="fas fa-shipping-fast"></i>
                <span class="links_name">Retourenverwaltung</span>
            </a>
            <span class="tooltip">Retourenverwaltung</span>
        </li>

        <li>
            <a asp-controller="UserManagement" asp-action="Index">
                <i class="fas fa-users"></i>
                <span class="links_name">Benutzerverwaltung</span>
            </a>
            <span class="tooltip">Benutzerverwaltung</span>
        </li>

        <partial name="_LoginPartial"/>
    </ul>
</div>

<div class="container body-content">
    @RenderBody()
    <footer>
        <p>&copy; 2021 - aweProject</p>
    </footer>
</div>


@RenderSection("Scripts", required: false)


<script>
    let sidebar = document.getElementById("sidebar");
    let closeBtn = document.getElementById("closeBtn");

    closeBtn.addEventListener("click", () => {
            sidebar.classList.toggle("open");
            menuBtnChange();
        });

    function menuBtnChange() {
        if (sidebar.classList.contains("open")) {
            closeBtn.classList.replace("bx-menu", "bx-menu-alt-right");
        } else {
            closeBtn.classList.replace("bx-menu-alt-right", "bx-menu");
        }
    }

    function openBarOnHome() {
        sidebar.classList.toggle("open");
        menuBtnChange();
    }
</script>

</body>
</html>