aweProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using aweProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace aweProject.Controllers
{
    public class AdminController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public AdminController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create(ProjectRole role)
        {
            var roleExist = await roleManager.RoleExistsAsync(role.RoleName);
            if (!roleExist)
            {
                var result = await roleManager.CreateAsync(new IdentityRole(role.RoleName));
            }
            return View();
        }
    }
}

aweProject/Controllers/UserManagementController.cs
using aweProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace aweProject.Controllers
{
    public class UserManagementController : Microsoft.AspNetCore.Mvc.Controller
    {

        private  AppDbContext _context;


        public UserManagementController(AppDbContext context)
        {
            _context = context;
        }

        [Microsoft.AspNetCore.Authorization.Authorize(Roles ="Administrator")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Roles = await _context.Roles.ToListAsync();
            return View(_context.Users.ToList());
        }

        [Microsoft.AspNetCore.Mvc.HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {
           
  
            UserRole userRole = new UserRole();
            var users = _context.Users.Where(x => x.Id == Id).SingleOrDefault();
            var userInRole = _context.UserRoles.Where(x => x.UserId == Id).Select(x => x.RoleId).ToList();
            userRole.applicationUser = users;

            userRole.ApplicationRoles = await _context.Roles.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id,
                Selected = userInRole.Contains(x.Id)
            }).ToListAsync();
            
            return View(userRole);
        }

        [Microsoft.AspNetCore.Mvc.HttpPost]
        public async Task<IActionResult> Edit (UserRole model)
        {
            var applicationUser = await _context.Users.FindAsync(model.applicationUser.Id);
            var selectedRoleId = model.ApplicationRoles.Where(x => x.Selected).Select(x => x.Value);
            var AlreadyExists = _context.UserRoles.Where(x => x.UserId == model.applicationUser.Id).Select(x => x.RoleId).ToList();
            var toAdd = selectedRoleId.Except(AlreadyExists);
            var toRemove = AlreadyExists.Except(selectedRoleId);
            foreach (var item in toRemove)
            {
                _context.UserRoles.Remove(new Microsoft.AspNetCore.Identity.IdentityUserRole<string>
                {
                    RoleId = item,
                    UserId = model.applicationUser.Id
                });
            }
            foreach (var item in toAdd)
            {
                _context.UserRoles.Add(new Microsoft.AspNetCore.Identity.IdentityUserRole<string>
                {
                    RoleId = item,
                    UserId = model.applicationUser.Id
                });
            }
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

aweProject/Views/UserManagement/Edit.cshtml
@model aweProject.Models.UserRole;

<div id="OrderCard">
    <div class="card border-dark" id="SiteFormPartialCard">
        <div class="card-header pl-3 pb-0 pt-2">
            <h4>Rollen bearbeiten</h4>
        </div>
        <div class="card-body">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class=" form-group">
                    <input type="hidden" asp-for="@Model.applicationUser.Id"  />
                    <label asp-for="@Model.applicationUser.Name">
                        Name :    @Model.applicationUser.Name
                    </label>
                </div>
                <div class="form-group">
                    @for (int i = 0; i< Model.ApplicationRoles.Count; i++)
                    {
                        <ul style="list-style-type: none">
                            <li>
                                <input type="hidden" asp-for="@Model.ApplicationRoles[i].Value" />
                                <input asp-for="@Model.ApplicationRoles[i].Selected" />@Model.ApplicationRoles[i].Text
                            </li>
                        </ul>
                        
                    }
                </div>
                <div class="form-group">
                    <input type="submit" value="Speichern" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>

aweProject/Views/UserManagement/Index.cshtml
@model IEnumerable<aweProject.Areas.Identity.Data.AppUser>

@{
    ViewData["Title"] = "Nutzerverwaltung";
}


<div id="OrderCard">
    <div class="card border-dark" id="SiteFormPartialCard">
        <div class="card-header pl-3 pb-0 pt-2">
            <h4>Registrierte Nutzer</h4>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">E-Mail</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int i = 1;
                        foreach (var item in Model)
                        {
                            <tr>
                                <th scope="row">@i</th>
                                <td scope="row">@Html.DisplayFor(modelItem => item.Name)</td>
                                <td scope="row">@Html.DisplayFor(modelItem => item.Email)</td>
                                <td scope="row"><a href='@Url.Action("Edit", "UserManagement", new { ID = item.Id })'>Berechtigungen bearbeiten</td>
                            </tr>
                            i++;
                        }
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="OrderCard">
    <div class="card border-dark" id="SiteFormPartialCard">
        <div class="card-header pl-3 pb-0 pt-2">
            <h4>Verfügbare Rollen</h4>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Rollename</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var j = 1;
                        foreach (var item in ViewBag.Roles)
                        {
                            <tr>
                                <th scope="row">@j</th>
                                <td scope="row">@item.Name</td>
                                <th scope="row"></th>
                            </tr>
                            j++;
                        }
                    }
                    <tr>
                        <th scope="row"></th>
                        <td scope="row"><a href="@Url.Action("Create", "Admin")">Rolle hinzufügen</td>
                        <td scope="row"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>